import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
// update 2024-08-16 11:15:36
// update 2024-08-19 11:22:43
// update 2024-09-16 8:10:35
// update 2024-09-18 8:34:40
// update 2024-09-24 16:24:59
// update 2024-09-25 12:6:32
// update 2024-10-04 12:20:34
// update 2024-10-09 12:57:28
// update 2024-08-12 9:26:55
// update 2024-08-13 9:36:49
// update 2024-08-13 11:2:17
// update 2024-08-20 15:33:59
// update 2024-08-15 10:8:1
// update 2024-08-23 8:17:42
// update 2024-10-16 16:58:35
// update 2024-12-04 15:49:47
// update 2024-12-05 8:9:43
// update 2024-12-17 11:19:59
// update 2024-10-19 12:8:29
